openapi: 3.0.0
info:
  title: Rooze API
  version: '1.0'
servers: []
tags: []
paths:
  /health:
    get:
      responses:
        '200':
          description: ''
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
  /styles/popular:
    get:
      parameters:
      - name: limit
        schema:
          type: integer
          format: uint64
        in: query
        required: false
        deprecated: false
        explode: true
      responses:
        '200':
          description: ''
          content:
            application/json; charset=utf-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Style'
components:
  schemas:
    Style:
      type: object
      title: Style
      required:
      - name
      properties:
        name:
          type: string
