openapi: 3.0.0
info:
  title: Rooze API
  version: '1.0'
servers: []
tags: []
paths:
  /health:
    get:
      responses:
        '200':
          description: ''
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
  /styles/popular:
    get:
      parameters:
      - name: limit
        schema:
          type: integer
          format: int64
        in: query
        required: true
        deprecated: false
        explode: true
      responses:
        '200':
          description: ''
          content:
            application/json; charset=utf-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PopularStyle'
        '500':
          description: ''
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
components:
  schemas:
    PopularStyle:
      type: object
      title: PopularStyle
      required:
      - count
      - id
      - name
      properties:
        count:
          type: integer
          format: int64
        id:
          type: integer
          format: int64
        name:
          type: string
