openapi: 3.0.0
info:
  title: Rooze API
  version: '1.0'
servers: []
tags: []
paths:
  /health:
    get:
      responses:
        '200':
          description: ''
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
  /styles/popular:
    get:
      parameters:
      - name: limit
        schema:
          type: integer
          format: int64
        in: query
        required: true
        deprecated: false
        explode: true
      responses:
        '200':
          description: ''
          content:
            application/json; charset=utf-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StyleWithCount'
        '500':
          description: ''
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
  /styles/by_bounds:
    get:
      parameters:
      - name: south_west_lat
        schema:
          type: number
          format: double
        in: query
        required: true
        deprecated: false
        explode: true
      - name: north_east_lat
        schema:
          type: number
          format: double
        in: query
        required: true
        deprecated: false
        explode: true
      - name: south_west_long
        schema:
          type: number
          format: double
        in: query
        required: true
        deprecated: false
        explode: true
      - name: north_east_long
        schema:
          type: number
          format: double
        in: query
        required: true
        deprecated: false
        explode: true
      responses:
        '200':
          description: ''
          content:
            application/json; charset=utf-8:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StyleTypeWithCount'
        '500':
          description: ''
          content:
            text/plain; charset=utf-8:
              schema:
                type: string
components:
  schemas:
    StyleTypeWithCount:
      type: object
      title: StyleTypeWithCount
      required:
      - id
      - name
      - count
      - style_type
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        count:
          type: integer
          format: int64
        style_type:
          type: string
    StyleWithCount:
      type: object
      title: StyleWithCount
      required:
      - id
      - name
      - count
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        count:
          type: integer
          format: int64
